CREATE DATABASE QUANLY_CUAHANG_BANXEMAY ON PRIMARY (
	NAME = 'QUANLY_CUAHANG_BANXEMAY',
	FILENAME = 'F:\QUANLY_CUAHANG_BANXEMAY.MDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 10%
)
GO

USE QUANLY_CUAHANG_BANXEMAY
GO

-- Tài khoản đăng nhập
CREATE TABLE TAIKHOAN (
	TAIKHOAN NVARCHAR(50),
	MATKHAU NVARCHAR(50),
	QUYENHAN NVARCHAR(50)
);

-- Nhân viên
CREATE TABLE NHANVIEN (
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50),
	CHUCVU NVARCHAR(50),
	EMAIL NVARCHAR(50),
	SDTNV VARCHAR(10)
);

-- Khách hàng
CREATE TABLE KHACHHANG (
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50),
	SDTKH VARCHAR(10),
	SOTIENCHI INT
);

-- Nhà cung cấp
CREATE TABLE NHACUNGCAP (
	MANCC VARCHAR(10) PRIMARY KEY,
	TENNCC NVARCHAR(50),
	DIACHI NVARCHAR(255),
	SDTNCC VARCHAR(10)
);

-- Xe máy
CREATE TABLE XEMAY (
	MAXE VARCHAR(10) PRIMARY KEY,
	TENXE NVARCHAR(50),
	HANGSX NVARCHAR(50),
	NAMSX VARCHAR(10),
	TINHTRANG NVARCHAR(50),
	NGUONGOC NVARCHAR(50),
	ANH VARBINARY(MAX)
);

-- Nhập hàng
CREATE TABLE NHAPHANG (
	MANHAP VARCHAR(10) PRIMARY KEY,
	NGAYNHAP DATE,
	TONGTIEN INT,
	MANV VARCHAR(10),
	MANCC VARCHAR(10),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

-- Chi tiết nhập hàng
CREATE TABLE CT_NHAPHANG (
	MANHAP VARCHAR(10),
	MAXE VARCHAR(10),
	SOLUONG INT,
	DONGIA INT,
	PRIMARY KEY (MANHAP, MAXE),
	FOREIGN KEY (MANHAP) REFERENCES NHAPHANG(MANHAP),
	FOREIGN KEY (MAXE) REFERENCES XEMAY(MAXE)
);

-- Bảo hiểm
CREATE TABLE BAOHIEM (
	MABH VARCHAR(10),
	MAXE VARCHAR(10),
	NGAYBATDAU DATE,
	THOIHAN DATE,
	PRIMARY KEY (MABH, MAXE),
	FOREIGN KEY (MAXE) REFERENCES XEMAY(MAXE)
);

-- Hóa đơn
CREATE TABLE HOADON (
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYLAP DATE,
	TONGTIEN INT,
	MAKH VARCHAR(10),
	MANV VARCHAR(10),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Chi tiết hóa đơn
CREATE TABLE CT_HOADON (
	MAHD VARCHAR(10),
	MAXE VARCHAR(10),
	SOLUONG INT,
	DONGIA INT,
	PRIMARY KEY (MAHD, MAXE),
	FOREIGN KEY (MAXE) REFERENCES XEMAY(MAXE),
	FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);

-- Thủ tục đăng nhập
CREATE PROCEDURE dangnhap (
	@ten NVARCHAR(50),
	@matkhau NVARCHAR(50)
)
AS
BEGIN
	SELECT t.QUYENHAN
	FROM TAIKHOAN t
	WHERE t.TAIKHOAN = @ten AND t.MATKHAU = @matkhau
END;


--  thong tin nha cung cap

	CREATE PROCEDURE themncc (
	@mancc VARCHAR(10),
	@tenncc NVARCHAR(50),
	@diachi NVARCHAR(255),
	@sdtncc VARCHAR(10)
)
AS
BEGIN
	INSERT INTO NHACUNGCAP (MANCC, TENNCC, DIACHI, SDTNCC)
	VALUES (@mancc, @tenncc, @diachi, @sdtncc);
END;


CREATE PROCEDURE xoanhacc (
    @mancc VARCHAR(10)
)
AS
BEGIN
    DELETE FROM NHACUNGCAP
    WHERE MANCC = @mancc;
END;


CREATE PROCEDURE suancc_dongian (
    @mancc VARCHAR(10),
    @tenncc NVARCHAR(50) = NULL,
    @diachi NVARCHAR(255) = NULL,
    @sdtncc VARCHAR(10) = NULL
)
AS
BEGIN
    UPDATE NHACUNGCAP
    SET
        TENNCC = COALESCE(@tenncc, TENNCC),
        DIACHI = COALESCE(@diachi, DIACHI),
        SDTNCC = COALESCE(@sdtncc, SDTNCC)
    WHERE MANCC = @mancc;
END;